FROM ubuntu:14.04

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends python-setuptools apt-transport-https ca-certificates wget rsync unzip jq && \
  easy_install pip==9.0.3 && \
  pip install ansible==2.4.0.0 pyasn1==0.3.6 ndg-httpsclient==0.4.3 urllib3==1.22 pyOpenSSL==17.3.0 && \
  pip install awscli --upgrade --user

RUN mkdir /root/bin

COPY tasks /aws/tasks
COPY site.yml site.yml
COPY deployment /aws/deployment

RUN ansible-playbook -i localhost -c local site.yml

