#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/../..

APPLICATION_NAME=`date +%s`
ENVIRONMENT_NAME=$APPLICATION_NAME

aws elasticbeanstalk create-application --application-name $APPLICATION_NAME

aws elasticbeanstalk create-environment --application-name $APPLICATION_NAME --environment-name $APPLICATION_NAME --solution-stack-name "64bit Amazon Linux 2015.03 v2.0.2 running Docker 1.7.1"

source $DIR/../../scripts/elastic_beanstalk_environment_update.sh

echo "Waiting for environment to start"

while [ "$(environment_status)" != "Ready" ] ; do
  sleep 10
  echo "."
done

mkdir -p tmp
echo "Creating Zip file to deploy"

bash -c "cd $DIR && zip -x */.git* -x .git* -x *.hg* -r $DIR/../../tmp/package.zip ./"

echo "Uploading to S3 for deployment"
aws s3 cp tmp/package.zip s3://elasticbeanstalkcodeupload

echo "Removing old ElasticBeanstalk version"
aws elasticbeanstalk delete-application-version --application-name $APPLICATION_NAME --version-label $CI_COMMIT_ID || true

echo "Creating ElasticBeanstalk version"
aws elasticbeanstalk create-application-version --application-name "$APPLICATION_NAME" --description "DESCRIPTION" --version-label "$CI_COMMIT_ID" --source-bundle "S3Bucket=elasticbeanstalkcodeupload,S3Key=package.zip"

echo "Updating ElasticBeanstalk environment"
aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $CI_COMMIT_ID

codeship_aws eb_deploy_validation $APPLICATION_NAME $ENVIRONMENT_NAME $CI_COMMIT_ID

function finish {
  echo "Removing ElasticBeanstalk running environment: $ENVIRONMENT_NAME"
  aws elasticbeanstalk terminate-environment --environment-name $ENVIRONMENT_NAME
  echo "Removing ElasticBeanstalk application: $APPLICATION_NAME"
  aws elasticbeanstalk delete-application --terminate-env-by-force  --application-name $APPLICATION_NAME
}

trap "finish" EXIT
trap "finish" ERR
