#!/bin/bash

set -e
set -o pipefail

APPLICATION_FOLDER=${1:?'You need to provide the directory with your code as the second parameter'}
APPLICATION_NAME=${2:?'You need to provide the CodeDeploy application name'}
DEPLOYMENT_GROUP_NAME=${3:?'You need to provide the Deployment Group name'}
S3_BUCKET=${4:?'You need to provide the S3 Bucket to upload the artefact to'}
DEPLOYMENT_CONFIG_NAME=$5

echo "Starting CodeDeploy deployment to $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME"

VERSION_NAME=${CI_COMMIT_ID}-${CI_BUILD_ID}-$(date +%Y-%m-%d.%H:%M:%S)
FILE_NAME=$VERSION_NAME.zip
S3_PATH=s3://$S3_BUCKET/$FILE_NAME


echo "application folder $APPLICATION_FOLDER"
echo "application name $APPLICATION_NAME"
echo "deployment group name $DEPLOYMENT_GROUP_NAME"
echo "S3 bucket $S3_BUCKET"
echo "deployment config name (optional) $DEPLOYMENT_CONFIG_NAME"

echo "ci commit id $CI_COMMIT_ID"
echo "commit message $COMMIT_MESSAGE"
echo "ci commit message $CI_COMMIT_MESSAGE"
echo "ci build id $CI_BUILD_ID"
echo "version name $VERSION_NAME"

aws deploy push --application-name "$APPLICATION_NAME" --description "$CI_COMMIT_MESSAGE" --ignore-hidden-files --s3-location "$S3_PATH" --source "$APPLICATION_FOLDER" > /dev/null

echo "Creating new Deployment: $VERSION_NAME"

deployment="aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-group-name $DEPLOYMENT_GROUP_NAME --description $CI_COMMIT_MESSAGE --s3-location bucket=$S3_BUCKET,key=$FILE_NAME,bundleType=zip"

echo "deployment! $deployment"

if [ ! -z "$DEPLOYMENT_CONFIG_NAME" ]; then
  deployment="$deployment --deployment-config-name $DEPLOYMENT_CONFIG_NAME"
fi

deployment_id=$($deployment | jq -r .deploymentId)

echo "Validating deployment: $deployment_id"
codeship_aws codedeploy_deploy_validation "$deployment_id"
