#!/bin/bash

set -e
set -o pipefail

APPLICATION_FOLDER=${1:?'You need to provide the directory with your code as the second parameter'}
APPLICATION_NAME=${2:?'You need to provide the Elastic Beanstalk application name'}
ENVIRONMENT_NAME=${3:?'You need to provide the Elastic Beanstalk environment name'}
S3_BUCKET=${4:?'You need to provide the S3 Bucket to upload the artefact to'}

source utils
S3_BUCKET_SUBFOLDER_PATH=$(s3_bucket_subfolder_path $S3_BUCKET)
S3_BUCKET=$(s3_bucket_name $S3_BUCKET)

echo "Starting ElasticBeanstalk deployment to $APPLICATION_NAME:$ENVIRONMENT_NAME"

echo "CHANGING Directory to $APPLICATION_FOLDER"
cd "$APPLICATION_FOLDER"

VERSION_NAME=${CI_COMMIT_ID}-${CI_BUILD_ID}-$(date +%Y-%m-%d.%H:%M:%S)
FILE_NAME=$VERSION_NAME.zip
DEPLOYMENT_FILE_NAME=/tmp/$FILE_NAME

if [[ -z $S3_BUCKET_SUBFOLDER_PATH ]]; then
  S3_KEY=$FILE_NAME
  S3_PATH="s3://$S3_BUCKET/$FILE_NAME"
else
  S3_KEY="$S3_BUCKET_SUBFOLDER_PATH/$FILE_NAME"
  S3_PATH="s3://$S3_BUCKET/$S3_BUCKET_SUBFOLDER_PATH/$FILE_NAME"
fi

echo "Creating Zip file to deploy in $DEPLOYMENT_FILE_NAME"
zip -x */.git* -x .git* -x *.hg* -r "$DEPLOYMENT_FILE_NAME" ./

echo "Uploading to S3 for deployment"

aws s3 cp "$DEPLOYMENT_FILE_NAME" "$S3_PATH"

echo "Creating ElasticBeanstalk version: $VERSION_NAME"

aws elasticbeanstalk create-application-version --application-name "$APPLICATION_NAME" --description "${CI_COMMIT_MESSAGE:0:200}" --version-label "$VERSION_NAME" --source-bundle "S3Bucket=$S3_BUCKET,S3Key=$S3_KEY"

echo "Updating ElasticBeanstalk environment"
aws elasticbeanstalk update-environment --environment-name "$ENVIRONMENT_NAME" --version-label "$VERSION_NAME"

echo "Validating deployment"
codeship_aws eb_deploy_validation "$APPLICATION_NAME" "$ENVIRONMENT_NAME" "$VERSION_NAME"
