#!/bin/bash

set -e
set -o pipefail

APPLICATION_FOLDER=${1:?'You need to provide the directory with your code as the second parameter'}
APPLICATION_NAME=${2:?'You need to provide the CodeDeploy application name'}
DEPLOYMENT_GROUP_NAME=${3:?'You need to provide the Deployment Group name'}
S3_BUCKET=${4:?'You need to provide the S3 Bucket to upload the artefact to'}
DEPLOYMENT_CONFIG_NAME=$5

source utils
S3_BUCKET_SUBFOLDER_PATH=$(s3_bucket_subfolder_path $S3_BUCKET)
S3_BUCKET=$(s3_bucket_name $S3_BUCKET)

echo "Starting CodeDeploy deployment to $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME"

VERSION_NAME=${CI_COMMIT_ID}-${CI_BUILD_ID}-${CI_TIMESTAMP}
FILE_NAME=$VERSION_NAME.zip

if [[ -z $S3_BUCKET_SUBFOLDER_PATH ]]; then
  S3_KEY=$FILE_NAME
  S3_PATH="s3://$S3_BUCKET/$FILE_NAME"
else
  S3_KEY="$S3_BUCKET_SUBFOLDER_PATH/$FILE_NAME"
  S3_PATH="s3://$S3_BUCKET/$S3_BUCKET_SUBFOLDER_PATH/$FILE_NAME"
fi

echo "Creating new Deployment: $VERSION_NAME"

deployment=("--application-name" "$APPLICATION_NAME" "--deployment-group-name" "$DEPLOYMENT_GROUP_NAME" "--description" "$CI_COMMIT_MESSAGE" "--s3-location" "bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip")

if [ ! -z "$DEPLOYMENT_CONFIG_NAME" ]; then
  deployment+=("--deployment-config-name" "$DEPLOYMENT_CONFIG_NAME")
fi

echo "Deployment Command: ${deployment[@]}"

deployment_id=$(aws deploy create-deployment "${deployment[@]}" | jq -r .deploymentId)

echo "Validating deployment: $deployment_id"
codeship_aws codedeploy_deploy_validation "$deployment_id"
